name: Update version if necessary

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          token: ${{ secrets.PAT }}
      - name: bump version
        # env:
        #   GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          ./bump-version.sh
      # - uses: EndBug/add-and-commit@v7
      #   with:
      #     add: "wagr-schema.svg"
      #     message: "Update schema image"
      #     branch: ${{ github.head_ref }}
