name: Update version if necessary and create new prerelease version of the package

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"
      - name: bump version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bump-version.sh
