name: Cleanup temp packages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: cleanup package versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./cleanup-packages.sh
